### ISSUE TITLE
HMD to controlled object - Axis re-mapping does not re-map also rotation order/rules 

### ISSUE THREAD

**Issue by RuiOrey** [borismus/webvr-boilerplate#39] opened 2015-10-16 15:25 UTC
UPDATE 28/10/2015: 

the problem is:  to map the VR controls to an object ( not the camera ) that has a different axis configuration and keep the correct rotation rules.
Example of object axis:
- x - up 
- y - depth
- z - side

```
//attach head tracker controller to object ( not camera )
controls = new THREE.VRControls( object );
```

Swapping the rotations by just
`object .rotation.x = object .rotation.z` results that, after updating the controls, rotating to the side makes an undesired rotation after 45º.

The rotation rules for each axis are different :
-    x rotates until PI and after that inverts signal and keeps changing in the same direction it was;
-    y rotates until PI/2 and after inverts the direction (when increasing, starts decreasing)
-    z is equal to x.

Changed `webvr-polyfill.js` and got it fixed for keyboard/mouse with this:

```
MouseKeyboardPositionSensorVRDevice.prototype.getState = function() {
   // this.euler.set(this.phi, this.theta, 0, 'YXZ');
   this.euler.set( this.theta , 0, - this.phi, 'YXZ');
```

But no way similar line to other controllers (HMD, cardboard, etc.).
Maybe it would be nice the rotation order and mapping could be available to the user.
Thanks

---

---

INITIAL QUESTION:

Hi,

I'm using your webvr-boilerplate and trying to map it to a human face mesh.

The way I do is is:

1) attach the camera to an eye bone and the neck bone to the VRControls

main js script:

```

//attach head tracker controller to neck bone
controls = new THREE.VRControls( mesh.skeleton.bones[ neckVRControlBone ] );

//add camera to eye
mesh.skeleton.bones[ 22 ].add(camera);

//resets camera rotation
camera.rotation.set(0,0,0);

//looks at mesh up direction to face front
camera.lookAt( mesh.up );

//moves camera to middle of eyes 
camera.position.set(10,10,0);
```

2) change the webvr-manager.js to update the neck bone ( passed as argument on initialization ) position and rotation and in index.php I swap the axis to match the HMD ones with the ones of the bone:

webvr-manager.js:

```
if ( state.orientation !== null ) {

    object.quaternion.copy( state.orientation );

}

if ( state.position !== null ) {

    //object.position.copy( state.position ).multiplyScalar( scope.scale );

}
```

main js script:

```
 /* INSIDE UPDATE CYCLE */

// mesh.rotation.y+=0.1;
controls.update();

//resets bone position to default
mesh.skeleton.bones[ neckVRControlBone ].position.set(neckInitPosition.x,neckInitPosition.y,neckInitPosition.z) ;

//rotates the mesh body with the neck

mesh.rotation.x = - mesh.skeleton.bones[ neckVRControlBone ].rotation.x; // UP - DOWN - PITCH

mesh.rotation.y =  mesh.skeleton.bones[ neckVRControlBone ].rotation.y; //  LEFT RIGHT - YAW

mesh.rotation.z =  - mesh.skeleton.bones[ neckVRControlBone ].rotation.z; //  INCLINE - ROLL

```

The problem is that there is a rotation restriction on the up HMD axis, that, after swapping the left/right bone axis with up/down HMD axis, constrains the left/right bone movement.
I've been looking at your files and I've seen this in `webvr-polyfill.js` :

```
  // Prevent looking too far up or down.
  //this.phi = this.clamp_(this.phi, -Math.PI/2, Math.PI/2);
```

However commenting this seems to me to have no effect.
Is this the right place?
Where can I change that? thanks!
[Example](http://ruidorey.webfactional.com/)

**Comment by borismus** [comment] 2015-10-23 02:53
What are you trying to do? Constrain all pitch motions? I'm thinking of adding an option for that in WebVRConfig.

**Comment by RuiOrey** [comment] 2015-10-23 05:34
Hi, what I want is the opposite, to remove the look up and down clamp/constrain that is being done to the "VRcontrolled" object and in my opinion should be done to the input axis before assignment of the values to the object as opposition to doing the clamp being applied on the object. 

Other solution was to swap the constrain to the yaw instead of pitch, depending on my object axes...

I commented some clamps at polyfill but didn't seemed to work.

As the axes are manually swapped by me in my bone neck, when I look 90 degrees to the left, the head flips. Can I remove or swap the clamp? How? 

Hope I'm not being very confusing.
Thanks!

**Comment by borismus** [comment] 2015-10-23 22:55
You'd have to change code for that.

**Comment by RuiOrey** [comment] 2015-10-24 13:05
I'll gladly do it but I cannot seem to find the code that clamps the pitch motion. As referred in my question, I've searched in webvr-boilerplate code and it's components code and the most approximate to that was in `webvr-polyfill.js` some clamps to phi, but commenting it out didn't seemed to remove the clamp in my application. If you or someone could point me where is that clamp happening, I would gladly change that by myself. Thanks

**Comment by borismus** [comment] 2015-10-25 23:54
Can you add this as a WebVRConfig option? The clamping only happens in
MouseKeyboard sensor.

**Comment by RuiOrey** [comment] 2015-10-26 16:17
Maybe I'm not understanding or I'm not explaining myself correctly...

... Tested on phones and the clamp or something similar seems to happen also when making the head look to the side 45> degrees. Bone behaves bad ...UNLESS the axis are not swapped.

Testing tomorrow on rift, but meanwhile you can test it here:

http://vrtest.ruidorey.webfactional.com/original_axis.html - there is not a axis swap between hmd input and bone axis. Making the model look to the side 45> degrees by looking up or down with mouse/phone orientations seems to make the rotation correctly. 

http://vrtest.ruidorey.webfactional.com/swapped_axis.html - I swapped the axis to the bone behave similar to hmd. Making the model look to the side 45> degrees by looking left or right with mouse/phone orientations seems to make the rotation bad. 

PS: the bone axes are in this picture:
![imgo2](https://cloud.githubusercontent.com/assets/53763/10734731/94c2dd70-7bfc-11e5-85e2-2d0bdc600076.jpeg)
Other hypothesis is that I'm using a rig that has some problem... but manually rotating the neck bone by three.js console or gui does not cause the head to flip...

And thank you a lot!

**Comment by RuiOrey** [comment] 2015-10-27 15:31
Ok, I've been further testing this case.
I've changed http://vrtest.ruidorey.webfactional.com/swapped_axis.html  to output the rotation x,y and z on the console and global booleans swappedAxis to swap the axis to the correct mapping or leave them with the original mapping, and rotateX, rotateY, rotateZ .. to enable/disable the rotation on each axis. 

After disabling axis one by one seems to show that the way it handles rotations depends on the axis in this way (on MouseKeyboard sensor and with Oculus Rift DK2):
- x rotates until PI and after that inverts signal and keeps changing in the same direction it was;
- y rotates until PI/2 and after inverts the direction (when increasing, starts decreasing)
- z is equal to x.

I think this is set on `webvr-polyfill.js`.
First I tried commenting these clamps:

```
  MouseKeyboardPositionSensorVRDevice.prototype.animatePhi_ = function(targetAngle) {

     // Prevent looking too far up or down.
     //targetAngle = this.clamp_(targetAngle, -Math.PI/2, Math.PI/2);

     this.animateKeyTransitions_('phi', targetAngle);
}; 
```

and comment a similar clamp in `MouseKeyboardPositionSensorVRDevice.prototype.onMouseMove_` .

But no result...I think is not related to that, but maybe the order of the axis.

With that in mind I was able to test also in `webvr-polyfill.js` :

```
MouseKeyboardPositionSensorVRDevice.prototype.getState = function() {
   // this.euler.set(this.phi, this.theta, 0, 'YXZ');
  this.euler.set( this.theta , 0, - this.phi, 'YXZ');
```

and this worked by 1.mapping the right axis and 2.making each rotation perform the correct angle but ONLY in mouse/keyboard mode.
I found a similar line in `GyroPositionSensorVRDevice.prototype.getOrientation` , more in specific `this.deviceEuler.set(beta, alpha, -gamma, 'YXZ');`, which I tried to change and no result..
I think I'm getting to it, do you know where can I do the same "re-mapping" of the euler order for cardboard and rift?

**Comment by RuiOrey** [comment] 2015-10-29 11:11
@borismus I updated the initial question and the title to try to be more direct...this is getting confusing, sorry for that. But the issue is not having a way to remap the axis and axis rotation rules ( defined in `webvr-polyfill` ) of an object that is VRControlled.

**Comment by borismus** [comment] 2015-10-29 19:01
Thanks for clarifying. However, still confused about what you mean by "keep the correct rotation rules". Also, this seems like something you can do outside the polyfill. 

Just attach the VRControls to another object (not your camera), and then do coordinate transforms there. Your best bet is probably to do the transformation using quaternion multiplication. The issue is outside the scope of the boilerplate so I'll close it.

If you disagree, please explain why and reopen :)

**Closed as completed by borismus** 2015-10-29 19:01 UTC

**Comment by RuiOrey** [comment] 2015-10-29 23:33
Thanks
I'll insist a last time :)

Ok, to be simpler:
http://vrtest.ruidorey.webfactional.com/swapped_axis.html <- Try to look left or right past 45 degrees from the initial rotation with the mouse or hmd.
Might be easier to understand what I'm talking about.

Now, what I do there is: 
1.attach the controls to an invisible pivot (a threejs default Object3D);
2.then at each update(), it runs :

```
controls.update();
mesh.skeleton.bones[ neckVRControlBone ].rotation.x = pivot.rotation.y;
mesh.skeleton.bones[ neckVRControlBone ].rotation.y = - pivot.rotation.z;
mesh.skeleton.bones[ neckVRControlBone ].rotation.z = - pivot.rotation.x;
```

I think it might be a polyfill question because it seems to me that it is making diferent transformations to the rotations depending on the axis BEFORE I map the pivot to the bone on each update.
While experimenting I got to the point that if I do this change in `polyfill`:

```
MouseKeyboardPositionSensorVRDevice.prototype.getState = function() {
    // this.euler.set(this.phi, this.theta, 0, 'YXZ');  //commenting this line
     this.euler.set( this.theta , 0, - this.phi, 'YXZ'); //replacing with this
```

 ..the axis swap (between pivot and bone) is no longer needed + the rotation to the side is fixed - but only for mouse/keyboard.
But I don't understand enough of rotations to securely state what is going on.. I think is somewhere between the axis order config (XYZ, YXZ, etc) , the axis mapping and the angle operations that polyfill does...
However, even being related to polyfill, and without wanting to sound too demanding :) I think the boilerplate could have an option to change the axis order XYZ, YXZ ,etc to map the rotation axis to other objects that not the camera easily..
Thanks a lot anyway

**Comment by RuiOrey** [comment] 2015-10-30 10:41
Forgot to mention you in my last comment @borismus what do you think?
If I understood how to do the same euler.set for MouseKeyboard  I did in polyfill but for HMD I would gladly make a contribution with what I have in mind...and then I would reopen :)

**Comment by borismus** [comment] 2015-10-31 00:29
Looks like you have a bug. I don't see what this has to do with polyfill,
sorry.

**Comment by RuiOrey** [comment] 2015-10-31 02:05
Ok, I'll try to look deeper into it. 
Thank you anyways.
