### ISSUE TITLE
Not correct distance between eyes in iPhone

### ISSUE THREAD

**Issue by iRomano** [borismus/webvr-boilerplate#105] opened 2016-01-18 18:32 UTC
Hi

When i'm watching your samples on iPhone, it have not correct distance between eyes.

How  fix it?

**Comment by borismus** [comment] 2016-01-20 01:23
Please elaborate. Which phone? How do you know the eye distance is incorrect? Which viewer?

**Comment by iRomano** [comment] 2016-01-20 06:46
@borismus 
iPhone 5s
Image is double

I seen your samples.
And i used your webvr-manager in my project.

And double image in cardboard.app. If used custom profile - it's ok. But in other apps image is good.

How can fix in webvr-manager?

**Comment by brianchirls** [comment] 2016-01-20 20:47
I can confirm this and offer some insight:

`determineIPhone_` only checks against the device width, and the iPhone 4 and iPhone 5 both have the same pixel width. So you have to match both the height and the width. But before we implement this, I'm not sure if there are any other phone models with vague screen dimensions where this might cause a problem.

That said, having tested that solution, it's not a sufficient fix. The [source of specs](http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions) for `DeviceInfo` code says iPhone 5 screen is 640 x 1136. If I simulate iPhone 5 in Chrome Dev Tools, it matches and the solution works fine. But when I try it on a real iPhone 5 _and_ the one in the simulator that comes with xcode, the resolution is 640 x 1096. It's missing 20 pixels (times the pixel ratio of 2).

I suspect this is related to #102.

**Comment by brianchirls** [comment] 2016-01-20 21:39
@borismus Have you considered using `screen.height` instead of `screen.availHeight`? It seems to make up the 20px discrepancy.

**Comment by borismus** [comment] 2016-01-20 23:19
Would avail\* solve the problem? You mention in your other post that there
were detection problems using availWidth.

**Comment by brianchirls** [comment] 2016-01-21 04:22
No, I don't think `availHeight` or `availWidth` is working because I'm seeing that 20px discrepancy that shows up. According to MDN, `screen.availWidth` is ["amount of horizontal space in pixels available to the window"](https://developer.mozilla.org/en-US/docs/Web/API/Screen/availWidth) and `screen.width` is [width of the screen](https://developer.mozilla.org/en-US/docs/Web/API/Screen/width). The latter gives the full screen dimension, which is unlikely to change, while the former is affected by whatever junk the OS decides to add.

I think we need to check _both_ `screen.width` and `screen.height`. I wanted to check with you before making a PR in case there was a specific reason you picked `availWidth` instead of `width` in the first place.

**Comment by iRomano** [comment] 2016-01-21 07:51
Hi!

Yes, i fixed this part:
 var width = screen.width;
  var height = screen.height;
  var pixelWidth = width \* window.devicePixelRatio;
  var pixelHeight = height \* window.devicePixelRatio;
  // Match the screen dimension to the correct device.
  for (var id in iOSDevices) {
    var device = iOSDevices[id];
    // Expect an exact match on width.
    if (device.width == pixelWidth && device.height == pixelHeight) {

Detect device = iPhone5

Whatever. 

I see double image if i used: CardboardV1 or CardboardV2

**Comment by brianchirls** [comment] 2016-01-22 15:56
It looks to me like #103 fixed this. It's using `screen.width` and `screen.height`, and my own code with #103 incorporated seems to look okay on my iPhone 5. (Though it's very slow, but that's a whole batch of other issues.)

@iRomano can you confirm?

@borismus Perhaps this is a good time to update the gh-pages branch?

**Comment by iRomano** [comment] 2016-01-22 16:59
@brianchirls 
Excellent, it's working! 
Thanks a lot!

P.S.
If use the dev version of the Three.js, stereo picture - don't work.
If take Three.js from your build - it's ok.

**Comment by brianchirls** [comment] 2016-01-22 17:03
@iRomano: Thank @btco for this one.

Getting three.js r74 to work here is a whole other project. There is an ongoing discussion here:
https://github.com/mrdoob/three.js/issues/7732

**Comment by iRomano** [comment] 2016-01-22 17:09
@brianchirls Thank you for the link.
@btco Thanks a lot!

**Comment by iRomano** [comment] 2016-02-18 19:24
Hi!

I downloaded new version webvr-boilerplate.
And i have same troubles:
iPhone 5s
Image is double

@btco
@borismus

**Comment by crookookoo** [comment] 2016-02-23 15:02
@iRomano @borismus 
Probably this: https://github.com/borismus/webvr-boilerplate/issues/115

**Comment by borismus** [comment] 2016-03-01 16:57
Assuming it's related to r74 and closing.

**Closed as completed by borismus** 2016-03-01 16:57 UTC

**Comment by brianchirls** [comment] 2016-03-03 03:56
@borismus: I don't believe this is specifically related to r74. It was _mostly_ fixed by #103, but there are at least a couple outstanding cases, including iPhones with Display Zoom turned on (see #102). And I think the default iPhone and Android devices are sometimes way off because the distortion is not centered...or something. Not sure.
