### ISSUE TITLE
Mouse look does not work when webvr API is available

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#62] opened 2015-11-11 20:52 UTC
It would be nice to have the option to use the mouse to look around when not in VR mode, but this is only available in browsers that don't support webvr directly. It seems that mouse control is implemented as a VR control device in the polyfill and that part is just skipped when the polyfill is not necessary.

Maybe mouse/touch should be implemented separately, since the functionality is complementary to VR device control.

**Comment by borismus** [comment] 2015-11-12 22:50
Noted. This can currently be done outside the boilerplate with OrbitControls.

**Comment by borismus** [comment] 2016-03-28 21:31
This is a duplicate of https://github.com/borismus/webvr-boilerplate/issues/82, let's continue discussion there.

**Closed as completed by borismus** 2016-03-28 21:31 UTC
