### ISSUE TITLE
Zorder incorrect in VR mode

### ISSUE THREAD

**Issue by tommytee** [borismus/webvr-boilerplate#57] opened 2015-11-05 20:52 UTC
example:
http://postfat.ninja/

notice blue in front, red in rear. then view in VR.

**Comment by brianpeiris** [comment] 2015-11-08 13:09
Looks ok to me. You might have been experiencing an issue with an earlier build of Chrome toji/chrome-webvr-issues#40. This was fixed in the latest Chrome build.

**Comment by tommytee** [comment] 2015-11-08 17:22
maybe... after a check:

problem - Safari iOS 9.1
problem - chrome 46.0.2490.73  iOS 9.1
problem - chrome 46.0.2490.76 android 5.1.1 SM-G920V LMY47X - Galaxy S6
problem - Chrome Dev 48.0.2553.4 android 5.1.1 SM-G920V LMY47X - Galaxy S6
problem - Opera Beta 33.0.2002.97240 android 5.1.1 SM-G920V LMY47X - Galaxy S6

 fine ----- Opera Beta 33.0.2002.97240 android 5.1.1 ONE A2005 LMY47V
 fine ----- chrome 46.0.2490.76 android 5.1.1 ONE A2005 LMY47V
 fine ----- chrome 46.0.2490.76 android 4.2.1
 fine ----- chrome 43.0.2357.92 android 4.4.2

**Comment by tommytee** [comment] 2015-11-08 18:50
seems to be a problem on Verizon firmware and iOS

**Comment by borismus** [comment] 2015-11-08 20:58
Confirm. I'm seeing the same thing in iOS. Could you see if it's distortion-related?

**Comment by tommytee** [comment] 2015-11-08 21:56
i see no change by setting FORCE_DISTORTION or DISTORTION_BGCOLOR in WebVRConfig.

**Comment by borismus** [comment] 2015-11-08 23:45
Hmm, I'm quickly out of ideas. Maybe @mrdoob?

**Comment by mrdoob** [comment] 2015-11-09 15:47
I can reproduce on Android (Chrome 46.0.2490.76, Android 6.0.0; Nexus 5 Build/MRA58K).

The fact that the problem is not there in specific versions of Chrome makes me think it's a Chrome/drivers issue. /cc @toji

The fact that the problem is there in Safari/Chrome iOS worries me though.

Does this happen with r71, r72 too?

**Comment by tommytee** [comment] 2015-11-09 17:06
It does happen on r72 and the latest 74dev.  not sure r71 is compatible... renderer.getSize()

**Comment by pushmatrix** [comment] 2015-11-10 03:05
I'm seeing it as well on r72 in Safari on iOS.

**Comment by mrdoob** [comment] 2015-11-11 04:24
https://github.com/borismus/webvr-boilerplate/issues/55#issuecomment-155657037

**Comment by tommytee** [comment] 2015-11-11 05:07
fix on #55 (comment)

**Comment by tommytee** [comment] 2015-11-27 18:29
https://github.com/borismus/webvr-boilerplate/commit/acfe5fe97e63cd7e60cbaa38657b4c4ef17549d1

depthBuffer: false
(should be removed, works for me)
https://github.com/borismus/webvr-boilerplate/blob/master/src/cardboard-distorter.js#L52

**Comment by borismus** [comment] 2015-12-01 17:36
@tommytee If you are still having issues with the current master (depthBuffer: false in the shader pass), please re-open. The depthBuffer is enabled on the first render pass, so the z-order should be correct.

**Closed as completed by borismus** 2015-12-01 17:36 UTC

**Comment by idlewan** [comment] 2015-12-01 17:55
It's actually the opposite currently, this `depthBuffer: false` applies to the first render pass, the shader pass doesn't use that render target as an output.

**Comment by borismus** [comment] 2015-12-01 18:02
Got it. Fixed in https://github.com/borismus/webvr-boilerplate/commit/f48f016dee7833fcf1522157e77913167f16cd7a
